name: Deploy test twa

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so job can access it
      - name: Checkout
        uses: actions/checkout@v4
      - name: JDK setup
        uses: actions/setup-java@v4 # See https://github.com/actions/setup-java
        with:
          distribution: 'temurin'
          java-version: '17.0.7'
      - name: Checkout env repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.ENV_REP_PATH }}
          token: ${{ secrets.ENV_REP_KEY }}
          path: temp
      - name: Set up envs
        run: |
          ls
          cp temp/lib/env/fire.env . -v
          mkdir lib/env -v
          cp temp/env.dart lib/env -v
          cp temp/lib/firebase_options.dart lib -v
      - name: Set up Flutter

        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.5
      - run: flutter --version
      - name: Pub get
        run: flutter pub get
      - name: Build envs
        run: dart run build_runner build
      - name: Build
        run: flutter build web --web-renderer canvaskit

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build_test
          FOLDER: ./build/web
          GITHUB_TOKEN: ${{ secrets.ENV_REP_KEY }}
          MESSAGE: "Build: ({sha}) {msg}" # The commit message

